name: pget
description: "A new command line tool for backup package versions and path"
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  args: ^2.4.0
  logger: ^2.0.1
  yaml: ^3.1.1
  yaml_edit: ^2.2.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

executables:
  pget: bin/pget.dart